name: Python CI

on:
  push:
    branches: ["main"]

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
    # step1
    - uses: actions/checkout@v4

    # step2
    - name: Set up Python
      uses: actions/setup-python@v5
      with: python-version:'3.10'
    
    # step4
    - name: Run Unit Tests
      run: python -m unittest test_find_max.py